// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9rTNBGiyGHUo6pJkFNrC7nMqX_kvy7IY',
    appId: '1:743079054366:web:35bd08f57535e3bf53b20f',
    messagingSenderId: '743079054366',
    projectId: 'cv-personal-app-dev',
    authDomain: 'cv-personal-app-dev.firebaseapp.com',
    storageBucket: 'cv-personal-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUblpIOZt88jlP1WWVqHiILIRRqNzxaG4',
    appId: '1:743079054366:android:2eb1673c7752f9b253b20f',
    messagingSenderId: '743079054366',
    projectId: 'cv-personal-app-dev',
    storageBucket: 'cv-personal-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBX6186d9CVThOVGpVOioHXDibdWsHTas',
    appId: '1:743079054366:ios:d437a1c2c00a2ba853b20f',
    messagingSenderId: '743079054366',
    projectId: 'cv-personal-app-dev',
    storageBucket: 'cv-personal-app-dev.firebasestorage.app',
    iosBundleId: 'com.david.cv.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBX6186d9CVThOVGpVOioHXDibdWsHTas',
    appId: '1:743079054366:ios:d437a1c2c00a2ba853b20f',
    messagingSenderId: '743079054366',
    projectId: 'cv-personal-app-dev',
    storageBucket: 'cv-personal-app-dev.firebasestorage.app',
    iosBundleId: 'com.david.cv.dev',
  );
}
