const List<String> aboutParagraph = [
  "Computer science and technology is the future, and the future is happening right now. As a former airline pilot, I seek to change my career path to the information and technology sector. Given the enormous impact that Covid-19 is having on the aviation industry, I consider this as an opportune time to adjourn from the industry and embark on a new chapter. As such, I am looking for an opportunity to work in an industry where I am genuinely passionate.",
  "During school, I was elected as head boy of Christian Brothers College Boksburg in South Africa (SA) and a head of house. These leadership positions provided me with the opportunity to gain valuable leadership skills at an early age. Upon graduation, my immediate ambition was to pursue a career in aviation. The training consisted of practical flying and numerous aviation-specific examinations – I graduated second in my class overall.",
  "I transitioned swiftly from student to teacher, obtaining an instructor rating at The Johannesburg School of Flying in SA. I worked there teaching other enthusiastic young mavericks as they began their aviation careers. My interpersonal skills were utilised effectively – teaching students to fly requires several communication techniques. Additionally, I motivated students and undertook my duties flexibly to tailor the learning experience for a wide range of skill levels that the students possessed. Furthermore, I participated in a range of different types of projects in a voluntary capacity. For example, I was involved in creating training handbooks for students and developing a mass and balance application to ensure the loading of the aircraft did not exceed legal limitations. This was where my passion for technology became apparent. Using technology to streamline operations was my new focus in the workplace. After that, I progressed to becoming a first officer on an Embraer 120 for TAB Charters based in SA. I gained further responsibility as I volunteered to build a flight-following application which was later deployed for use as part of the company’s standard operations. This was used for aircraft and crew tracking, which helped to increase safety and awareness.",
  "Since then, I have been increasing my knowledge in programming through online courses and independent research. Doing so provided me with the necessary skills to create a website for another charter company to manage its client quote requests and provide users with general company information. At present, I am also a co-founder of a start-up company aiming to build an education collaboration platform for learners to share information and notes to assist in learner-to-learner aid. Apart from completing online courses, such as Flutter and ASP.Net Core frameworks, I am also completing a software engineering bootcamp through HyperionDev to help further my knowledge in the field. I have learnt a foundation of software engineering material that ranges from coding experience to data analysis and engineering best practices. This has fuelled my ambitions to work towards creating innovative technology that can make a difference.",
  "I am currently enrolled as a part-time student at Open University, studying a BA/BSc (Honours) Open Degree tailored to computing and IT. I began my studies in 2019, intending to finish first-year credits by September 2021. I have gained knowledge in the computing field and am always building my expertise in the area. I am also an avid sports enthusiast enjoying golf, rugby, swimming and keeping fit in general. Maintaining a balanced lifestyle is key to physical and mental health and happiness, which is essential to me.",
  "I am ambitious and self-motivated and capable of synergising well with others in a group environment. I desire to acquire new knowledge, and I possess the drive needed to pursue this new career path. Thus, I am confident I would be a valuable asset and contributor to the working environment."
];

const String profileDescription = "Aspiring Software Engineer with a passion for technology. Ambitious learner actively working to upskill himself and grow within a professional role.";
